In [2]:
# Importing numpy
import numpy as np

In [3]:
# 1. printing numpy version
print(np.__version__)

1.16.5


In [12]:
# 2. Creating array
# 1-dimensional array
a = np.array([1,2,3])
print("1 dimesional array",a)
# 2-dimensional array
b = np.array([[2,3,4],[3,5,6]])
print("2 dimesional array", b)

1 dimesional array [1 2 3]
2 dimesional array [[2 3 4]
 [3 5 6]]


In [18]:
# 3. data type of array elements
b.dtype

dtype('int32')

In [19]:
# 4. Number of array elements
b.size

6

In [22]:
# 5. Number of array dimensions 
b.ndim

2

In [23]:
# 6. Array dimensions
b.shape

(2, 3)

In [25]:
# 7. Name of data type 
b.dtype.name


'int32'

In [30]:
# 8. Create an array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
# 9. Create an array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
# 10. Create an empty array
np.empty((2,4))

array([[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 5.83e-321, 0.00e+000, 0.00e+000]])

In [37]:
# 11. Create a identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
# 12. Create a constant array
np.full((2,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [43]:
# 13. Create an array of evenly spaced values (step value)
np.arange(1,27,5)

array([ 1,  6, 11, 16, 21, 26])

In [49]:
# 14.Create an array of evenly spaced values (number of samples) 
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [54]:
# 15. Create an array with random values
np.random.random((5,5))

array([[0.81649373, 0.07334268, 0.51739855, 0.95169481, 0.35800614],
       [0.04549641, 0.86504754, 0.917286  , 0.605428  , 0.484781  ],
       [0.47209053, 0.01553168, 0.04221822, 0.82364084, 0.78507853],
       [0.11862237, 0.44476022, 0.23910577, 0.59749669, 0.35948131],
       [0.0653237 , 0.63816036, 0.40836708, 0.87165114, 0.74989798]])

In [64]:
# 16. Convert an array to a different type
a.astype(str)


array(['1', '2', '3'], dtype='<U11')

In [59]:
# 17. Asking For Help 
np.info(np.arange)

arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``

In [133]:
# 18. Subtraction
np.subtract(a,b) 

array([[-1, -1, -1],
       [-2, -3, -3]])

In [67]:
# 19. Addition
np.add(b,a)

array([[3, 5, 7],
       [4, 7, 9]])

In [69]:
# 20. Division
np.divide(b,a)

array([[2.        , 1.5       , 1.33333333],
       [3.        , 2.5       , 2.        ]])

In [70]:
# 21. Multiplication
np.multiply(a,b)

array([[ 2,  6, 12],
       [ 3, 10, 18]])

In [73]:
# 22. Exponentiation
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [74]:
# 23. Square root
np.sqrt(b)

array([[1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.23606798, 2.44948974]])

In [75]:
# 24. Element-wise cosine
np.cos(b)

array([[-0.41614684, -0.9899925 , -0.65364362],
       [-0.9899925 ,  0.28366219,  0.96017029]])

In [76]:
# 25. Element-wise sines
np.sin(b)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [ 0.14112001, -0.95892427, -0.2794155 ]])

In [78]:
# 26. Element-wise natural logarithm
np.log(b)

array([[0.69314718, 1.09861229, 1.38629436],
       [1.09861229, 1.60943791, 1.79175947]])

In [187]:
# 27. Dot product
a.dot(a)

14

In [100]:
# 28. Array comparison(equal)
np.equal(a,b)

array([[False, False, False],
       [False, False, False]])

In [103]:
# 29. Array-wise sum
b.sum()

23

In [106]:
# 30. Array-wise minimum value
b.min()

2

In [107]:
# 31. Maximum value of array
b.max()

6

In [109]:
# 32. Mean
b.mean()

3.8333333333333335

In [117]:
# 33. Median
np.median(b)

3.5

In [119]:
# 34. Correlation coefficient
np.corrcoef(b)

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

In [120]:
# 35. Standard deviation
np.std(b)

1.3437096247164249

In [125]:
# 36. Create a view of the array with the same data
d = b.view()

In [130]:
# 37. Create a copy of the array
f = np.copy(b)

In [140]:
# 38. Sort an array
f = np.array([[2,1,5],[4,6,9]])
f.sort()
print(f)

[[1 2 5]
 [4 6 9]]


In [141]:
# 39. Transposing Array
np.transpose(b)

array([[2, 3],
       [3, 5],
       [4, 6]])

In [143]:
# 40. Make array 1 dimensional
b.ravel()

array([2, 3, 4, 3, 5, 6])

In [175]:
# 41. Reshape array
b.reshape(3,-1)

array([[2, 3],
       [4, 3],
       [5, 6]])

In [157]:
# 42. Append items to an array
np.append(a,b)

array([1, 2, 3, 2, 3, 4, 3, 5, 6])

In [162]:
# 43. Insert items in an array
np.insert(a, 0, 5) 

array([5, 1, 2, 3])

In [171]:
# 44. Delete items from an array
print(b)
np.delete(b,[1])

[[2 3 4]
 [3 5 6]]


array([2, 4, 3, 5, 6])

In [214]:
# 45. Concatenate arrays
a = np.array([1,2,4])
b = np.array([3,2,6])
np.concatenate((a,b))

array([1, 2, 4, 3, 2, 6])

In [195]:
# 46. Stack arrays vertically 
a = np.array([1,2,4])
b = np.array([3,2,6])
np.vstack((b,a))

array([[3, 2, 6],
       [1, 2, 4]])

In [196]:
# 47. Create stacked column-wise arrays
np.column_stack((a,b))

array([[1, 3],
       [2, 2],
       [4, 6]])

In [198]:
# 48. Split the array horizontally
np.hsplit(a,3)

[array([1]), array([2]), array([4])]

In [210]:
# 49. Split the array vertically
c=np.arange((9)).reshape((3,3))
np.vsplit(c,3)


[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [212]:
# 50. Reversed array
print(a)
a[::-1]

[1 2 4]


array([4, 2, 1])